name: good_reads_app
description: An app for readers that showcases bestseller books and allows users to make recommendations for books
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  logger: ^1.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
